[tool.black]
line-length = 120

[tool.poetry]
name = "compilesketches"
version = "0.0.0"
description = ""
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "3.11.2"
GitPython = "3.1.41"
PyGithub = "2.2.0"
PyYAML = "6.0.1"
semver = "3.0.2"

[tool.poetry.group.dev.dependencies]
black = "24.2.0"
codespell = "2.2.6"
coverage = "7.4.1"
pytest = "8.0.0"
pytest-mock = "3.12.0"
flake8 = "7.0.0"
pep8-naming = "0.13.3"
yamllint = "1.35.0"

[tool.poetry.group.external]
# Provided only for use by boards platforms
# NOTE: This group is a temporary workaround that will be removed at the 2.0.0 release of the action.
optional = true

[tool.poetry.group.external.dependencies]
pyserial = "3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
